### ISSUE TITLE
event_sender wrong event calculation

### ISSUE THREAD

**Issue by alrapal** [ItJustWorksTM/EiffelVis#115]
# Event sender sends double the event asked

## Description: 
* When giving the parameter -c 25 -b 2, the total of the event sent is 100. 
* This is the same for other combination of numbers
* The number of event displayed on the front end is corresponding to the double amount of events expected. 

## How to reproduce the bug:
* run the event_sender giving any -c and -b parameters combined-
* Observe that the total event number is doubled in the console, but also in the frontend

## Screenshots:
<img width="1438" alt="Screenshot 2022-10-21 at 15 34 47" src="https://user-images.githubusercontent.com/71485862/197213847-638e97c4-2bee-4b72-8786-8dd8db08261c.png">

We can take a look at it since we are working on the generator anyway, if it's okay with you guys?

**Comment by RuthgerD** [comment]
https://github.com/ItJustWorksTM/EiffelVis/blob/master/backend/tools/event_sender/src/main.rs#L113

`for _ in 0..(target) {`

would need to be `cli.count` instead, so this is indeed a bug :)

**Comment by RuthgerD** [comment]
Since it took 10 seconds to deduce the bug feel free to make a fix.

**Comment by alrapal** [comment]
Ok, we will fix this. Just posted here for traceability and for transparency =)
