### ISSUE TITLE
event_sender & backend -> rabbitMQ connection issues

### ISSUE THREAD

**Issue by alrapal** [ItJustWorksTM/EiffelVis#116]
# Problem with connecting event_sender and backend

## Description: 

I have a little problem with connecting the backend and the event_sender
I run the event sender using `hello` as routing key and the default `amp.fanout` exchange. 

`cargo run -- --routing-key hello -c 25 -b 2`

However, when I run the backend, it does not receive the event send because there is no binding happening and we cannot give the routing key as a parameter. So I have to go into the RabbitMQ management and bind manually the fanout exchange to the queue `hello` created by the backend. 

Is this intended or am I missing something? 😅 

## How to reproduce the bug:
* rabbitMQ default configuration
* run `cargo run -- --routing-key hello` in the event_sender repository
* run `cargo run --`in the backend repository
* Observe that backend does not receive events from broker 

### State of the amq.fanout before manual binding
<img width="1502" alt="not_binded" src="https://user-images.githubusercontent.com/71485862/197220948-5f9e51ea-36ea-43bc-9f92-85c49775476b.png">

### state of amq.fanout after binding
<img width="1505" alt="manually_binded" src="https://user-images.githubusercontent.com/71485862/197221090-4a366768-41a0-4891-aa4a-19294d55a29a.png">

**Comment by RuthgerD** [comment]
You're right that you need to configure the broker manually to make the messages reach the right place.
If you study the rabbitmq docs a bit you can find there are various tricks to manage your queues & co, this way is just the simplest (for us). 

Might be an area where Axis can chime in on how they usually do it.

Anyways, nothing actionable here so closing.

**Comment by alrapal** [comment]
Thanks for the heads explanation! 
See ya!
