### ISSUE TITLE
Suggestion: Add parameters to backend and event_sender to connect without rabbitmq manipulation

### ISSUE THREAD

**Issue by alrapal** [ItJustWorksTM/EiffelVis#120]
Hello!
Hope you are doing great :D ! 
Following our discussion #116, we think it would be interesting to be able to connect the event_sender and the backend without having to go into rabbit-mq parameters. 

We could add a queue parameter to the event_sender and/or a routing key parameter to the backend which would make it faster to get the system running while developing as well as make it more flexible. 

Do you have any insights or thoughts around this?

**Comment by RuthgerD** [comment]
Like I said before I am not a rabbitmq expert in any way so ask the Axis people for what makes sense regarding it,
you might already know more than me at this point.

Though the amount of work you need to do to setup rabbitmq takes like 2 minutes maybe so I don't think this brings much value, unless you have a patch ready ofcourse..

**Comment by alrapal** [comment]
OK, we wanted to check with you first, since this si more of development effort improvement. And sure, it only takes a few minutes to set up. 
Anyway a PR with the generator modification (the one you reviewed a bit on the forked repo) is on the way and we added some steps on the readme regarding the event sender and rabbitmq connection. Maybe next years student will also work on this, who know haha!  
We will see if we want to spent time on this or not. (We had something internally but it was not very clean since it was more out of convenience for us) 
Thanks for the inputs, we'll let you know if we decide to explore that road
