### ISSUE TITLE
lazy load graph

### ISSUE THREAD

**Issue by IdreesSamadi** [ItJustWorksTM/EiffelVis#17]
## Lazy Load

To ensure that the graph can be available for the users without having to worry about loading time. If the size of the data increases exponentially, the size of the graph will also increase exponentially, which in turn causes the loading time to increase. To make sure the graph is scalable with data size, we are proposing a solution in this RFC.

Goals:

* Decrease loading/rendering time for graph
* User is able to view the most recent events
* As the user zooms out/scrolls through the graph, the sections which the user can now view are rendered

Lazy loading avoids loading the entire graph at once. We can load the data as it comes to the viewport. What this means is that the Graph will be rendered based on the user's position on the canvas. As the user navigates across the graph by scrolling or zooming out,  the rest of the graph is rendered based on what the user can currently view.

**Comment by RuthgerD** [comment]
Especially considering we are targeting to be real-time, but we do have to consider how expensive it is to recalculate the entire graph as you're adding / removing new nodes to the data set that is being rendered.

**Comment by RuthgerD** [comment]
Is this still something we can do?

**Comment by RuthgerD** [comment]
semi - implemented by ranged queries which allows to look at a small portion of the entire graph that the backend stored
