### ISSUE TITLE
Instance drawing

### ISSUE THREAD

**Issue by IdreesSamadi** [ItJustWorksTM/EiffelVis#18]
## Instance Drawing

Once again, we need to ensure that the graph is scalable with data size. To reduce rendering time, we are using [Performance Optimization](https://g-next.antv.vision/en/docs/guide/advanced-topics/performance-optimization) so that the graph can be loaded faster. 

Goals: 
* Reduce rendering time for graph
* Objects outside the viewport will not be rendered

This helps reduce the number of drawing commands issued as it copies shapes which have already been rendered instead of drawing new shapes.

**Comment by RuthgerD** [comment]
I don't think this is a controversial thing to implement instanced rendering and such so removed the RFC tag :^).

**Comment by RuthgerD** [comment]
I believe this isn't very relevant atm (its already enabled by default now with g6?)
