### ISSUE TITLE
Layout Design for Data Visualization

### ISSUE THREAD

**Issue by SyncInProgress** [ItJustWorksTM/EiffelVis#33]
## Design Idea

![image](https://user-images.githubusercontent.com/57683502/140759207-73ffd851-b91e-42f9-bab7-05c6623c32c6.png)

By [Cambridge Intelligence](https://cambridge-intelligence.com/the-basics-of-timeline-data-visualization/)

## Algorithm

After much consideration and planning, we figured the best algorithm for our layout would be based on [Sugiyama's Layered Graph](https://en.wikipedia.org/wiki/Layered_graph_drawing) and [Brandes-Kopf's Horizontal Coordinate Assignment](https://www.semanticscholar.org/paper/Fast-and-Simple-Horizontal-Coordinate-Assignment-Brandes-K%C3%B6pf/69cb129a8963b21775d6382d15b0b447b01eb1f8).

## Implementation

To implement these algorithms, we are using the [Dagre library](https://github.com/dagrejs/dagre). While the layout is somewhat similar to what we expected before choosing the algorithm's, the complexity increases drastically as the number of events increases. One reason for this is that the library cannot calculate the layers or ranks of nodes until it knows how many nodes and relations exist, which means that the calculation is done recursively instead of being done iteratively. 

There are two ways to fix this which we will be working on. 
* [Trampolining](https://raganwald.com/2013/03/28/trampolines-in-javascript.html)
* Using [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) to decrease calculation times

**Comment by sodero** [comment]
Looks very nice. Let's hope performance doesn't become a showstopper.

**Comment by RuthgerD** [comment]
Here is what we might be settling on, pictures taken from private conversation.
A very simplistic but bullet proof algorithm that might actually just work.

x axis is time, y axis is events sharing the same time

2 examples below:

A more friendly event set, events generated with a short allowed history to link to:
![image](https://user-images.githubusercontent.com/57626200/142193072-248305df-7f42-4d41-9227-d3c874415485.png)
A pretty harsh event set where events can link as far as 100 events back:
![image](https://user-images.githubusercontent.com/57626200/142193103-828f4ce1-b1df-4749-9cd4-80f45ac1a2ef.png)
Same settings as above, less events:
![image](https://user-images.githubusercontent.com/57626200/142193744-ab5cda14-555a-46da-91e7-0cfd4d12170e.png)

The real killer here is when new events links back to "very" old events
