### ISSUE TITLE
possibly replace tweakpane with Bootstrap

### ISSUE THREAD

**Issue by IdreesSamadi** [ItJustWorksTM/EiffelVis#45]
currently tweakpane widget is used to serve as input field for controlling and adding filters to the graph, while it seemed convenient at the begin it adds unnecessary dependency. besides it doesn't proved the input field needed for this project.

**Comment by IdreesSamadi** [comment]
@RuthgerD

**Comment by RuthgerD** [comment]
We still need to expand our filter catalog, but a good example of what we need is a date time picker such that the user can select a range of events. this range can be unbounded on both sides.

another one is the Ids filter where you can filter for an arbitrary list of even ids, we might want to have some integration for this one where the user can choose to add the selected node to the list.

And in general we want to better integrate the values shown in the panel with what the current state of the networking is, as there might be invalid queries made.

**Comment by RuthgerD** [comment]
fixed with #74
