### ISSUE TITLE
Backend project layout

### ISSUE THREAD

**Issue by RuthgerD** [ItJustWorksTM/EiffelVis#6]
Before we go and start writing code it will be good to discuss how we will organize our code.

First off I'd like to discuss what crates can / need to exist, and after that define some loose rules on where we place our files.

### eiffelvis_core (lib):
Our secret sauce, its responsibility will be to provide the means of managing an Eiffel event graph.

The reasoning behind this crate is that we don't have to compile an entire web framework along with our hopefully lightweight core logic. Things like benchmarking and testing do not need networking.

Likely dependencies:
* ?

### eiffelvis_server (bin):
Basically the end product, it will have:
1. RabbitMQ connectivity to stream in events
2. An HTTP API that will allow poking around the Eiffel graph and enable our frontend.

Likely dependencies:
* axum + hyper
* tokio + futures
* tower + tower-http
* tracing + tracing-subscriber
* lapin + tokio-amqp
* eiffelvis_core

### eiffel_mock (lib) (name bikesheddable):
Will generate "realistic" events with valid `Links` between them, specially needed to perf/bug test our system.
Both the frontend, `eiffelvis_server` and `eiffelvis_core` will benefit from this in tests and benches.

Likely dependencies:
* serde + serde_json

A note on this is that we should not constrain ourselves to pipe these generated events over RabbitMQ and instead provide a clean API for the consumer to integrate.

## Alternative extra crates
We can also choose to also split out all networking into their own crates:  `eiffelvis_http` (lib), `eiffelvis_amqp` (lib).
With `eiffelvis` (bin) that combines all aforementioned crates into a product we'd like to ship.

An `eiffelvis_amqp` in particular would be interesting as we can aim for it to simply provide a `Stream` (from the `futures` crate) of events. With a bit of coordination `eiffel_mock` would also provide a stream like API, and swapping each one would be awesome.

If we make `eiffelvis_core` good enough to provide a general querying API then `eiffelvis_http` would only be a simple wrapper instead of containing a lot of logic.

## File Layout
Regardless of crates we can define some rules on where we place our files.

Our final binary:
`/*`

Using the top-level `Cargo.toml` and `src` directory

Libraries:
`/crates/$name`

with `$name` being a folder containing a Cargo.toml

Unit tests:
Simply in the file itself, or in a lib.rs or mod.rs if you're testing larger parts of a library:
```rust
// ^^^ implementation code
#[cfg(test)]
mod tests {
    // tests here
}
```

Integration tests:
`/tests/*`

Here we test things like hooking up the event generator over RabbitMQ, reading those events and then querying the HTTP API all in one go.

Benchmarks:
`/benches/*`

**Comment by RuthgerD** [comment]
Once we come to a consensus on the layout, I will go ahead and setup all the Cargo machinery needed to support it all.
Before that though I will probably write another issue for discussing `eiffelvis_core` as it's public api is still highly in flux

**Comment by AeroStun** [comment]
LGTM, +1

**Comment by sodero** [comment]
I like the ideas under 'Alternative extra crates'. I think you should go in that direction. Overall, LGTM.
