### ISSUE TITLE
Eiffel Event generator strategy

### ISSUE THREAD

**Issue by RuthgerD** [ItJustWorksTM/EiffelVis#7]
## Summary

This RFC discusses the general direction of our planned eiffel event generator library. A simple api + some types are coined but more advanced details will have to come later.

Our primary objective is "speed", in discussion we have not found a large need for event correctness / completeness and will assume that the events `eiffelvis_core` will process will only contain the bare minimum of information consisting of at least meta .id and links [ type + target ] and time.

We take advantage of this here to keep the implementation drastically simple and only focus on producing valid event chains.

Goals:
* Produce easily configurable eiffel event chains
* Be configurable to cover many test cases
* Focus on supporting `eiffelvis_core` 
  
Non Goals:
* Produce events that would be considered valid by the spec
* Throw serialization into the mix

An example of this is that meta.type and link types will likely just be random arbitrary strings (within reason).

### User facing:
An ideal user api would look like this:

```rust
let chain = RandomEventChainBuilder::default()
    .links(0..10) // Range of the amount of random links each event should have
    .link_age(0..20) // Amount of steps the generator can look back when making a new link (to allow discarding old ids)
    .amount(1000) // total amount of events that should be generated
    .seed("hi")
    // .? im not very creative thinking of customization points
    .iter();

// Lazy evalutation
for event in chain {
    // do something
    put_into_graph(event);
}

// Or precalculate everything at once
let events = chain.collect();
```

This api is highly configurable and fits many cases, for example setting `link_age` to 0 and `links` to 1..1 will basically produce singly linked list. 

The iterator will produce a gutted Eiffel Event type:

```rust
#[derive(Serialize, Deserialize)]
struct Meta {
    id: String,
    #[serde(rename = "type")]
    event_type: String,
    version: String,
    time: i64
    // Not high priority?
    // source: Source
    // security: Security
}
#[derive(Serialize, Deserialize)]
struct Link {
    #[serde(rename = "type")]
    link_type: String,
    target: String
}
#[derive(Serialize, Deserialize)]
struct Event<T: Serialize + Deserialize> {
    meta: Meta
    data: T, 
    links: Vec<Link>
}
```

With T being undecided as of writing.

This new type should warrant a new crate `eiffelvis_types` so that it can be shared with `eiffelvis_core` in the case where we want to standardise what a good event would look like.

### Details:
Generating the events should be quite straight forward,
the `EventIterator` only needs to keep track of an array of past UUID + links to reference.

The `.links(<Range>)` configurable will need some careful attention so that we can generate many different graphs.
For example we should allow the user to set a custom distribution from which we sample the amount of links an event will have so that we can generate many small sub graphs or fewer large sub graphs.

The `rand` and `rand_distr` crates will help out with this.

### Are we sure we don't care about the actual eiffel vocabulary?
Likely, if we want to produce a bit more genuine data we should extend the proposed `eiffelvis_types` to include a huge enum defining all the types (Like RemRem). But this will likely force us to serialize the produced data as `eiffelvis_core` will definitely be doing something else.

Though it's not too far fetched as it only takes one line to deserialize into a type everyone likes:
```rust
chain.map(|event| serde_json::from_slice(&event)).collect();
```

but will just clutter the api in many cases.

### Should the event generator have some more powers like `links` and `link_age`?
This is really just a question I'm not entire sure. maybe we should allow configuring the amount of link types there are.

**Comment by sodero** [comment]
About the actual eiffel vocabulary part: I think this comes down to how far we'll come in this project. Sooner or later we will end up discussing filtering, for a start it will be about time, windows and so on, and perhaps we won't have time to go beyond that. If we run into the problem of having too much time (a very rare problem), then we can consider more, let's say, semantic filtering that requires more than just the links. If we decide that we want / can do something like that, then the event generator needs to cater for this as well.

**Comment by RuthgerD** [comment]
> If we decide that we want / can do something like that, then the event generator needs to cater for this as well.

I've been thinking about filtering and such a bit more since I believe it's quite important to consider when building the foundation of EiffelVis (so that we don't paint ourselves into a corner) and the event generator will indeed need to be considered along with it.

As the discussion section suggests, emitting the JSON representation instead of a known type will probably help message the ambiguity of the event. Then later in development we can extend the abilities of the generator to create more valid Eiffel vocabulary types as more fields are being used. (With the small cost of serialization, but it's part of the puzzle anyways)

e.g. when the back-end tries to use valid fields and it errors out we know to upgrade the generator.

PS: Thanks for reading the RFC, will make more of these as we progress.

**Comment by sodero** [comment]
> PS: Thanks for reading the RFC, will make more of these as we progress.

No problem, it's well written and appreciated. I'll try to keep track of your issues and provide feedback as often as I can.

**Comment by RuthgerD** [comment]
As I moved to implement this, I quickly noticed the need for specifying different types of links with different referencing rules and came to the solution of having these "meta" types that describe the rules of an event when generating:

```rust
struct EventType {
    name: String,
    version: String,
    links: Vec<LinkType>,
}

struct LinkType {
    name: String,
    targets: Vec<String>,
    allow_many: bool,
    required: bool,
}
```

This also sets us up to support the data field of eiffel vocabulary but it's a bit too complex to support from the get go (that would need lost of random data generation)

I haven't really zoned in a good api for this yet though, experiments are here:
https://github.com/ItJustWorksTM/EiffelVis/blob/badmvp/backend/crates/eiffelvis_gen/src/lib.rs
