### ISSUE TITLE
EiffelVis Core: Event storage

### ISSUE THREAD

**Issue by RuthgerD** [ItJustWorksTM/EiffelVis#8]
## Fast event storage.

To support accessing and inserting many many events at any given moment we need a specialized container that supports that kind of thing. This RFC proposes a solution to this problem.

Goals:
* Fast insertion - we cannot fall behind the stream of incoming events
  * \+ Minimal locking - the HTTP api should not be able to easily hog a lock on the event storage.
* Fast lookup - we should not be searching around all over for a single event
* Fast iteration - filters and other queries should not be slow
* Scaling memory use
  
Non goals:
* Tiny total memory footprint
* Keep around events forever

Credits to @aerostun for thinking big

## Graph representation

At it's core an Eiffel event is just a node in a [directed acyclic graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph), it can link back to n events that came before it.

Eiffel vocabulary uses UUIDv4 to identify and link back events, and naturally to store an event in memory you quickly put it into an HashMap with the id as a key.

It's a great start but suffers from bad iteration speed due to the sparse memory layout.

We can mitigate this by making use of the ordered never changing history of events, instead of storing events in a map we can store them in a continuous array and replace the UUID with an index. This way we gain fast iteration, instant lookup and given we pre-allocate a lot of memory fast appending as well.

We then only need to use a HashMap to translate the original UUID to the index, and luckily this type of container already exists in the form of [`IndexMap`](https://github.com/bluss/indexmap).

Though we should consider making our own container to properly apply our assumptions with proper memory allocation.

## Node representation

So we will use an `IndexMap`, but what kind of data do we store inside it?

We want to keep the Node itself tiny to keep fast iteration so:

1. A vector of indices, these will serve as the links for the Eiffel event. The container for this should use SBO so that we can fit a handful of links without allocating (given we use a small index type like u16) -> [SmallVec](https://crates.io/crates/smallvec).

2. An owning pointer to the original event, to keep the node small

A node existing in a graph is already its identifier so we do not need to store it.

side note: As our arrays will never reach `usize` limits so a sensible optimization would be to shrink the index type to `u16` or `u32`

Code sample:
```rust
struct Node<T> {
    event: T,
    links: Vec<IndexType>
}

// T = Box<Event> - or any alternative
```

### Discussion:

1. A single pointer to the Eiffel event will likely cause a bunch of cold memory access, we have to consider storing things like the time on the Node itself to balance it out.
2. This is a singly linked node, trying to find out which events point to a certain event will require an O(n) operation, we could consider reversing the link direction on insertion. (For other reasons we may require this, see below)

## Memory management

With the graph representation we assume that we never reallocate, this comes with the cost of having a limit on how many events that can be stored. Pre-allocation is not an issue, until you try to do it for an obscene amount.

We need a mechanism of dynamically allocating medium sized chunks to put our events into and a way to do that is by storing multiple graphs as described above inside a vector.

This will slightly complicate our indices as they are now not 100% contiguous anymore, to still make them work a byte of the original index type needs to be used to store in which graph they are in.

### Problem: how do we free memory?

With indices that can reference multiple separate arrays how do we ever delete very old events when they are still being referenced? We can't allow a node to link to an invalid node or even the wrong node.  
Options:
1. Find all references and safely remove them / zero them out; costly  .
2. Wait until nobody references them anymore; Kinda impossible  .
3. Reverse the link direction as described in the Node representation discussion 2, this removes the back reference problem; slows down insertion (and we technically get a doubly linked list, inside the original event we still have the link UUIDs).

## Discussion
* Will filtering by time be efficient using this?  
YES, we can use binary search to zone in on a chunk of events in a certain time span. other forms of filtering don't enjoy this speed though :^)
* Will the frontend be exposed to this special indexing?  
While it would be great a optimization, the problem with back-referencing still exists while the UUID is unique™ (checkable if dropped) so we will have to just send them the UUID.
* How is concurrent access dealt with?  
The arrays themselves are technically thread-safe as they are read-only (assuming custom impl vs `IndexMap`) but a lock is likely still required for the UUID <-> index map, a lockless alternative would be great.
* Is there an alternative?  
I believe this uses most optimization tricks the properties of an Eiffel event give us, nothing can really beat indexing an array but alternatives to the same idea exist.
* Is this premature optimization?  
Yes, but also necessary in the long run; if we theorize now we can take it into account later.
* Do you have a working implementation?  
No, all theory based..

CC @aerostun @efenaty

I had to write this out to properly evaluate the idea for myself, but it became RFC sized.

**Comment by sodero** [comment]
> side note: As our arrays will never reach usize limits so a sensible optimization would be to shrink the index type to u16 or u32

Please keep in mind that modern CPU:s generally don't appreciate working with < 32 bit words.

> Find all references and safely remove them / zero them out; costly .

If you do this periodically it might be feasible. Perhaps we can take advantage of the fact that references most of the time don't go all the way back in time, so even though it's o(n), in practice o(longest reference) might be a lot smaller.

**Comment by RuthgerD** [comment]
> If you do this periodically it might be feasible.

Yes Ryan had the same idea, and extending to that if we parallelize it it could be quite fast.
The only concern is that a sudden influx of events could catch you with your pants down, or just a constant stream not giving you a break.

Only way to know is to benchmark all the options :)

**Comment by sodero** [comment]
> Yes Ryan had the same idea, and extending to that if we parallelize it it could be quite fast.

Could it be done in a lock free manner?

> The only concern is that a sudden influx of events could catch you with your pants down, or just a constant stream not giving you a break.

> Only way to know is to benchmark all the options :)

Indeed. My guess is that it takes a massive influx for this to be a problem. One must keep in mind that RabbitMQ is a queue and therefore sort of a buffer. If it's just a temporary peak the messages will be there waiting for you until you have time to process them. A constant stream is a different story though.

**Comment by RuthgerD** [comment]
So I implemented a rough approximation of the storage described in the rfc, leaving a couple of things out (See the PR above).

I've been a bit stuck on the graph api itself rather than the backing storage implementation and I feel like we just have to move forward with something if we want to make progress and let things grow organically as demand grows from the frontend.

But to facilitate proper bench-marking and comparisons between alternative graph storage implementations we need a unified `Graph` trait so that there is a common interface. This should need it's own RFC though as it's hard to encapsulate everything as each implementation would have its own perf "short cuts" like custom internal indices.

So I propose plan "Make the whole stack work first":
1. Get "some" event storage working
2. Give it basic functionality
3. Hook up networking (which in itself also requires careful thought :/ tbh )
4. Unify interfaces and start bench-marking

**Comment by RuthgerD** [comment]
#40 brought up the quality of this a lot, closing as it's in a working state now.
